version: 2

jobs:
  deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/mixspa-example
    steps:
      - checkout
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build
          command: yarn build
      - run:
          name: Git deploy
          command: bash ./ci/deploy.sh

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
